name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: flightdb
        options: >-
          --health-cmd="pg_isready -U admin -d flightdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Backend - Install dependencies and run tests
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Fix Jest Permissions
      working-directory: ./backend
      run: chmod +x ./node_modules/.bin/jest

   git add .github/workflows/ci-cd.yml - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 -U admin && echo "PostgreSQL is ready" && exit 0
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL did not become ready in time" && exit 1


    - name: Set Backend Environment Variables
      run: |
        echo DATABASE_HOST=db >> $GITHUB_ENV
        echo DATABASE_USER=admin >> $GITHUB_ENV
        echo DATABASE_PASSWORD=secret >> $GITHUB_ENV
        echo DATABASE_NAME=flightdb >> $GITHUB_ENV
        echo DATABASE_PORT=5432 >> $GITHUB_ENV

    - name: Run Backend Tests
      working-directory: ./backend
      env:
        DATABASE_HOST: ${{ env.DATABASE_HOST }}
        DATABASE_USER: ${{ env.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ env.DATABASE_NAME }}
        DATABASE_PORT: ${{ env.DATABASE_PORT }}
      run: npx jest --runInBand

    # Frontend - Install dependencies and build
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker Compose
      run: |
        docker-compose down
        docker-compose up --build -d

    - name: Verify Services are Running
      run: docker ps
